using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Runtime.InteropServices;

namespace VisualStudioProvider.PDB.raw
{
    [ComImport, Guid("cb787b2f-bd6c-4635-ba52-933126bd2dcd"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IDiaSymbol
    {
        int get_symIndexId(ref uint pRetVal);
        int get_symTag(ref uint pRetVal);
        int get_name(out string pRetVal);
        int get_lexicalParent(IDiaSymbol[] pRetVal);
        int get_classParent(IDiaSymbol[] pRetVal);
        int get_type(IDiaSymbol[] pRetVal);
        int get_dataKind(ref uint pRetVal);
        int get_locationType(ref uint pRetVal);
        int get_addressSection(ref uint pRetVal);
        int get_addressOffset(ref uint pRetVal);
        int get_relativeVirtualAddress(ref uint pRetVal);
        int get_virtualAddress(ref ulong pRetVal);
        int get_registerId(ref uint pRetVal);
        int get_offset(ref int pRetVal);
        int get_length(ref ulong pRetVal);
        int get_slot(ref uint pRetVal);
        int get_volatileType(ref int pRetVal);
        int get_constType(ref int pRetVal);
        int get_unalignedType(ref int pRetVal);
        int get_access(ref uint pRetVal);
        int get_libraryName(out string pRetVal);
        int get_platform(ref uint pRetVal);
        int get_language(ref uint pRetVal);
        int get_editAndContinueEnabled(ref int pRetVal);
        int get_frontEndMajor(ref uint pRetVal);
        int get_frontEndMinor(ref uint pRetVal);
        int get_frontEndBuild(ref uint pRetVal);
        int get_backEndMajor(ref uint pRetVal);
        int get_backEndMinor(ref uint pRetVal);
        int get_backEndBuild(ref uint pRetVal);
        int get_sourceFileName(out string pRetVal);
        int get_unused(string pRetVal);
        int get_thunkOrdinal(ref uint pRetVal);
        int get_thisAdjust(ref int pRetVal);
        int get_virtualBaseOffset(ref uint pRetVal);
        int get_virtual(ref int pRetVal);
        int get_intro(ref int pRetVal);
        int get_pure(ref int pRetVal);
        int get_callingConvention(ref uint pRetVal);
        int get_value(object pRetVal);
        int get_baseType(ref uint pRetVal);
        int get_token(ref uint pRetVal);
        int get_timeStamp(ref uint pRetVal);
        int get_guid(ref Guid pRetVal);
        int get_symbolsFileName(out string pRetVal);
        int get_reference(ref int pRetVal);
        int get_count(ref uint pRetVal);
        int get_bitPosition(ref uint pRetVal);
        int get_arrayIndexType(IDiaSymbol[] pRetVal);
        int get_packed(ref int pRetVal);
        int get_constructor(ref int pRetVal);
        int get_overloadedOperator(ref int pRetVal);
        int get_nested(ref int pRetVal);
        int get_hasNestedTypes(ref int pRetVal);
        int get_hasAssignmentOperator(ref int pRetVal);
        int get_hasCastOperator(ref int pRetVal);
        int get_scoped(ref int pRetVal);
        int get_virtualBaseClass(ref int pRetVal);
        int get_indirectVirtualBaseClass(ref int pRetVal);
        int get_virtualBasePointerOffset(ref int pRetVal);
        int get_virtualTableShape(IDiaSymbol[] pRetVal);
        int get_lexicalParentId(ref uint pRetVal);
        int get_classParentId(ref uint pRetVal);
        int get_typeId(ref uint pRetVal);
        int get_arrayIndexTypeId(ref uint pRetVal);
        int get_virtualTableShapeId(ref uint pRetVal);
        int get_code(ref int pRetVal);
        int get_function(ref int pRetVal);
        int get_managed(ref int pRetVal);
        int get_msil(ref int pRetVal);
        int get_virtualBaseDispIndex(ref uint pRetVal);
        int get_undecoratedName(out string pRetVal);
        int get_age(ref uint pRetVal);
        int get_signature(ref uint pRetVal);
        int get_compilerGenerated(ref int pRetVal);
        int get_addressTaken(ref int pRetVal);
        int get_rank(ref uint pRetVal);
        int get_lowerBound(IDiaSymbol[] pRetVal);
        int get_upperBound(IDiaSymbol[] pRetVal);
        int get_lowerBoundId(ref uint pRetVal);
        int get_upperBoundId(ref uint pRetVal);
        int get_dataBytes(uint cbData, ref uint pcbData, ref byte pbData);
        int findChildren(SymTagEnum symtag, string name, uint compareFlags, out IDiaEnumSymbols ppResult);
        int findChildrenEx(SymTagEnum symtag, string name, uint compareFlags, IDiaEnumSymbols[] ppResult);
        int findChildrenExByAddr(SymTagEnum symtag, string name, uint compareFlags, uint isect, uint offset, IDiaEnumSymbols[] ppResult);
        int findChildrenExByVA(SymTagEnum symtag, string name, uint compareFlags, ulong va, IDiaEnumSymbols[] ppResult);
        int findChildrenExByRVA(SymTagEnum symtag, string name, uint compareFlags, uint rva, IDiaEnumSymbols[] ppResult);
        int get_targetSection(ref uint pRetVal);
        int get_targetOffset(ref uint pRetVal);
        int get_targetRelativeVirtualAddress(ref uint pRetVal);
        int get_targetVirtualAddress(ref ulong pRetVal);
        int get_machineType(ref uint pRetVal);
        int get_oemId(ref uint pRetVal);
        int get_oemSymbolId(ref uint pRetVal);
        int get_types(uint cTypes, ref uint pcTypes, IDiaSymbol[] pTypes);
        int get_typeIds(uint cTypeIds, ref uint pcTypeIds, ref uint pdwTypeIds);
        int get_objectPointerType(IDiaSymbol[] pRetVal);
        int get_udtKind(ref uint pRetVal);
        int get_undecoratedNameEx(uint undecorateOptions, string name);
        int get_noReturn(ref int pRetVal);
        int get_customCallingConvention(ref int pRetVal);
        int get_noInline(ref int pRetVal);
        int get_optimizedCodeDebugInfo(ref int pRetVal);
        int get_notReached(ref int pRetVal);
        int get_interruptReturn(ref int pRetVal);
        int get_farReturn(ref int pRetVal);
        int get_isStatic(ref int pRetVal);
        int get_hasDebugInfo(ref int pRetVal);
        int get_isLTCG(ref int pRetVal);
        int get_isDataAligned(ref int pRetVal);
        int get_hasSecurityChecks(ref int pRetVal);
        int get_compilerName(string pRetVal);
        int get_hasAlloca(ref int pRetVal);
        int get_hasSetJump(ref int pRetVal);
        int get_hasLongJump(ref int pRetVal);
        int get_hasInlAsm(ref int pRetVal);
        int get_hasEH(ref int pRetVal);
        int get_hasSEH(ref int pRetVal);
        int get_hasEHa(ref int pRetVal);
        int get_isNaked(ref int pRetVal);
        int get_isAggregated(ref int pRetVal);
        int get_isSplitted(ref int pRetVal);
        int get_container(IDiaSymbol[] pRetVal);
        int get_inlSpec(ref int pRetVal);
        int get_noStackOrdering(ref int pRetVal);
        int get_virtualBaseTableType(IDiaSymbol[] pRetVal);
        int get_hasManagedCode(ref int pRetVal);
        int get_isHotpatchable(ref int pRetVal);
        int get_isCVTCIL(ref int pRetVal);
        int get_isMSILNetmodule(ref int pRetVal);
        int get_isCTypes(ref int pRetVal);
        int get_isStripped(ref int pRetVal);
        int get_frontEndQFE(ref uint pRetVal);
        int get_backEndQFE(ref uint pRetVal);
        int get_wasInlined(ref int pRetVal);
        int get_strictGSCheck(ref int pRetVal);
        int get_isCxxReturnUdt(ref int pRetVal);
        int get_isConstructorVirtualBase(ref int pRetVal);
        int get_RValueReference(ref int pRetVal);
        int get_unmodifiedType(IDiaSymbol[] pRetVal);
        int get_framePointerPresent(ref int pRetVal);
        int get_isSafeBuffers(ref int pRetVal);
        int get_intrinsic(ref int pRetVal);
        int get_sealed(ref int pRetVal);
        int get_hfaFloat(ref int pRetVal);
        int get_hfaDouble(ref int pRetVal);
        int get_liveRangeStartAddressSection(ref uint pRetVal);
        int get_liveRangeStartAddressOffset(ref uint pRetVal);
        int get_liveRangeStartRelativeVirtualAddress(ref uint pRetVal);
        int get_countLiveRanges(ref uint pRetVal);
        int get_liveRangeLength(ref ulong pRetVal);
        int get_offsetInUdt(ref uint pRetVal);
        int get_paramBasePointerRegisterId(ref uint pRetVal);
        int get_localBasePointerRegisterId(ref uint pRetVal);
    }
}
